// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: EnumMessage.proto

package zpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandList int32

const (
	CommandList_MT_INVALID           CommandList = 0
	CommandList_MT_SERVER_TYPE_START CommandList = 1
	// MT_TO_SERVER
	// MT_ADD_COMPONENT
	CommandList_MT_ADD_ENGINE_COMPONENT CommandList = 2
	// MT_CENTER_TO_OTHER
	CommandList_MT_ADD_ENGINE_COMPONENT_ACK  CommandList = 10
	CommandList_MT_ADD_ENGINE_COMPONENT_LIST CommandList = 11
	// MT_CLIENT_TO_GATE
	CommandList_MT_GET_ALL_LOGIN_COMPONENT CommandList = 20
	// MT_TO_ALL
	CommandList_MT_SYNC_PROXY_PROPERTY CommandList = 30
	CommandList_MT_SET_REMOTE_PROPERTY CommandList = 31
)

// Enum value maps for CommandList.
var (
	CommandList_name = map[int32]string{
		0:  "MT_INVALID",
		1:  "MT_SERVER_TYPE_START",
		2:  "MT_ADD_ENGINE_COMPONENT",
		10: "MT_ADD_ENGINE_COMPONENT_ACK",
		11: "MT_ADD_ENGINE_COMPONENT_LIST",
		20: "MT_GET_ALL_LOGIN_COMPONENT",
		30: "MT_SYNC_PROXY_PROPERTY",
		31: "MT_SET_REMOTE_PROPERTY",
	}
	CommandList_value = map[string]int32{
		"MT_INVALID":                   0,
		"MT_SERVER_TYPE_START":         1,
		"MT_ADD_ENGINE_COMPONENT":      2,
		"MT_ADD_ENGINE_COMPONENT_ACK":  10,
		"MT_ADD_ENGINE_COMPONENT_LIST": 11,
		"MT_GET_ALL_LOGIN_COMPONENT":   20,
		"MT_SYNC_PROXY_PROPERTY":       30,
		"MT_SET_REMOTE_PROPERTY":       31,
	}
)

func (x CommandList) Enum() *CommandList {
	p := new(CommandList)
	*p = x
	return p
}

func (x CommandList) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandList) Descriptor() protoreflect.EnumDescriptor {
	return file_EnumMessage_proto_enumTypes[0].Descriptor()
}

func (CommandList) Type() protoreflect.EnumType {
	return &file_EnumMessage_proto_enumTypes[0]
}

func (x CommandList) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandList.Descriptor instead.
func (CommandList) EnumDescriptor() ([]byte, []int) {
	return file_EnumMessage_proto_rawDescGZIP(), []int{0}
}

var File_EnumMessage_proto protoreflect.FileDescriptor

var file_EnumMessage_proto_rawDesc = []byte{
	0x0a, 0x11, 0x45, 0x6e, 0x75, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x7a, 0x70, 0x62, 0x2a, 0xef, 0x01, 0x0a, 0x0b, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x54, 0x5f, 0x49,
	0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x4d, 0x54, 0x5f, 0x53,
	0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54,
	0x10, 0x01, 0x12, 0x1b, 0x0a, 0x17, 0x4d, 0x54, 0x5f, 0x41, 0x44, 0x44, 0x5f, 0x45, 0x4e, 0x47,
	0x49, 0x4e, 0x45, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4f, 0x4e, 0x45, 0x4e, 0x54, 0x10, 0x02, 0x12,
	0x1f, 0x0a, 0x1b, 0x4d, 0x54, 0x5f, 0x41, 0x44, 0x44, 0x5f, 0x45, 0x4e, 0x47, 0x49, 0x4e, 0x45,
	0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4f, 0x4e, 0x45, 0x4e, 0x54, 0x5f, 0x41, 0x43, 0x4b, 0x10, 0x0a,
	0x12, 0x20, 0x0a, 0x1c, 0x4d, 0x54, 0x5f, 0x41, 0x44, 0x44, 0x5f, 0x45, 0x4e, 0x47, 0x49, 0x4e,
	0x45, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4f, 0x4e, 0x45, 0x4e, 0x54, 0x5f, 0x4c, 0x49, 0x53, 0x54,
	0x10, 0x0b, 0x12, 0x1e, 0x0a, 0x1a, 0x4d, 0x54, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x41, 0x4c, 0x4c,
	0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4f, 0x4e, 0x45, 0x4e, 0x54,
	0x10, 0x14, 0x12, 0x1a, 0x0a, 0x16, 0x4d, 0x54, 0x5f, 0x53, 0x59, 0x4e, 0x43, 0x5f, 0x50, 0x52,
	0x4f, 0x58, 0x59, 0x5f, 0x50, 0x52, 0x4f, 0x50, 0x45, 0x52, 0x54, 0x59, 0x10, 0x1e, 0x12, 0x1a,
	0x0a, 0x16, 0x4d, 0x54, 0x5f, 0x53, 0x45, 0x54, 0x5f, 0x52, 0x45, 0x4d, 0x4f, 0x54, 0x45, 0x5f,
	0x50, 0x52, 0x4f, 0x50, 0x45, 0x52, 0x54, 0x59, 0x10, 0x1f, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x3b,
	0x7a, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_EnumMessage_proto_rawDescOnce sync.Once
	file_EnumMessage_proto_rawDescData = file_EnumMessage_proto_rawDesc
)

func file_EnumMessage_proto_rawDescGZIP() []byte {
	file_EnumMessage_proto_rawDescOnce.Do(func() {
		file_EnumMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_EnumMessage_proto_rawDescData)
	})
	return file_EnumMessage_proto_rawDescData
}

var file_EnumMessage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_EnumMessage_proto_goTypes = []interface{}{
	(CommandList)(0), // 0: zpb.CommandList
}
var file_EnumMessage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_EnumMessage_proto_init() }
func file_EnumMessage_proto_init() {
	if File_EnumMessage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_EnumMessage_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_EnumMessage_proto_goTypes,
		DependencyIndexes: file_EnumMessage_proto_depIdxs,
		EnumInfos:         file_EnumMessage_proto_enumTypes,
	}.Build()
	File_EnumMessage_proto = out.File
	file_EnumMessage_proto_rawDesc = nil
	file_EnumMessage_proto_goTypes = nil
	file_EnumMessage_proto_depIdxs = nil
}
