// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: ProxyMessage.proto

package zpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// @group {"name" : "PROXY_CMD", "id" : 1}
type Property struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    int32  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	PInt    int32  `protobuf:"varint,2,opt,name=p_int,json=pInt,proto3" json:"p_int,omitempty"`
	PString string `protobuf:"bytes,3,opt,name=p_string,json=pString,proto3" json:"p_string,omitempty"`
	PFloat  uint64 `protobuf:"varint,4,opt,name=p_float,json=pFloat,proto3" json:"p_float,omitempty"`
	PBool   bool   `protobuf:"varint,5,opt,name=p_bool,json=pBool,proto3" json:"p_bool,omitempty"`
}

func (x *Property) Reset() {
	*x = Property{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ProxyMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_ProxyMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_ProxyMessage_proto_rawDescGZIP(), []int{0}
}

func (x *Property) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Property) GetPInt() int32 {
	if x != nil {
		return x.PInt
	}
	return 0
}

func (x *Property) GetPString() string {
	if x != nil {
		return x.PString
	}
	return ""
}

func (x *Property) GetPFloat() uint64 {
	if x != nil {
		return x.PFloat
	}
	return 0
}

func (x *Property) GetPBool() bool {
	if x != nil {
		return x.PBool
	}
	return false
}

type PropertyMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   int32     `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value *Property `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PropertyMap) Reset() {
	*x = PropertyMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ProxyMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PropertyMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyMap) ProtoMessage() {}

func (x *PropertyMap) ProtoReflect() protoreflect.Message {
	mi := &file_ProxyMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyMap.ProtoReflect.Descriptor instead.
func (*PropertyMap) Descriptor() ([]byte, []int) {
	return file_ProxyMessage_proto_rawDescGZIP(), []int{1}
}

func (x *PropertyMap) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *PropertyMap) GetValue() *Property {
	if x != nil {
		return x.Value
	}
	return nil
}

// @message
type ADD_ENGINE_COMPONENT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        int32  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	ListenAddr  string `protobuf:"bytes,2,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	ComponentId int32  `protobuf:"varint,3,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
}

func (x *ADD_ENGINE_COMPONENT) Reset() {
	*x = ADD_ENGINE_COMPONENT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ProxyMessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ADD_ENGINE_COMPONENT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ADD_ENGINE_COMPONENT) ProtoMessage() {}

func (x *ADD_ENGINE_COMPONENT) ProtoReflect() protoreflect.Message {
	mi := &file_ProxyMessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ADD_ENGINE_COMPONENT.ProtoReflect.Descriptor instead.
func (*ADD_ENGINE_COMPONENT) Descriptor() ([]byte, []int) {
	return file_ProxyMessage_proto_rawDescGZIP(), []int{2}
}

func (x *ADD_ENGINE_COMPONENT) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ADD_ENGINE_COMPONENT) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

func (x *ADD_ENGINE_COMPONENT) GetComponentId() int32 {
	if x != nil {
		return x.ComponentId
	}
	return 0
}

// @message
type ADD_ENGINE_COMPONENT_ACK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ComponentId   int32                   `protobuf:"varint,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	Type          int32                   `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	ComponentList []*ADD_ENGINE_COMPONENT `protobuf:"bytes,3,rep,name=component_list,json=componentList,proto3" json:"component_list,omitempty"`
}

func (x *ADD_ENGINE_COMPONENT_ACK) Reset() {
	*x = ADD_ENGINE_COMPONENT_ACK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ProxyMessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ADD_ENGINE_COMPONENT_ACK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ADD_ENGINE_COMPONENT_ACK) ProtoMessage() {}

func (x *ADD_ENGINE_COMPONENT_ACK) ProtoReflect() protoreflect.Message {
	mi := &file_ProxyMessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ADD_ENGINE_COMPONENT_ACK.ProtoReflect.Descriptor instead.
func (*ADD_ENGINE_COMPONENT_ACK) Descriptor() ([]byte, []int) {
	return file_ProxyMessage_proto_rawDescGZIP(), []int{3}
}

func (x *ADD_ENGINE_COMPONENT_ACK) GetComponentId() int32 {
	if x != nil {
		return x.ComponentId
	}
	return 0
}

func (x *ADD_ENGINE_COMPONENT_ACK) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ADD_ENGINE_COMPONENT_ACK) GetComponentList() []*ADD_ENGINE_COMPONENT {
	if x != nil {
		return x.ComponentList
	}
	return nil
}

// @message
type SYNC_PROXY_PROPERTY struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropertyMapList []*PropertyMap `protobuf:"bytes,1,rep,name=property_map_list,json=propertyMapList,proto3" json:"property_map_list,omitempty"`
}

func (x *SYNC_PROXY_PROPERTY) Reset() {
	*x = SYNC_PROXY_PROPERTY{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ProxyMessage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SYNC_PROXY_PROPERTY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SYNC_PROXY_PROPERTY) ProtoMessage() {}

func (x *SYNC_PROXY_PROPERTY) ProtoReflect() protoreflect.Message {
	mi := &file_ProxyMessage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SYNC_PROXY_PROPERTY.ProtoReflect.Descriptor instead.
func (*SYNC_PROXY_PROPERTY) Descriptor() ([]byte, []int) {
	return file_ProxyMessage_proto_rawDescGZIP(), []int{4}
}

func (x *SYNC_PROXY_PROPERTY) GetPropertyMapList() []*PropertyMap {
	if x != nil {
		return x.PropertyMapList
	}
	return nil
}

// @message
type SET_REMOTE_PROPERTY struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropertyMapList []*PropertyMap `protobuf:"bytes,1,rep,name=property_map_list,json=propertyMapList,proto3" json:"property_map_list,omitempty"`
}

func (x *SET_REMOTE_PROPERTY) Reset() {
	*x = SET_REMOTE_PROPERTY{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ProxyMessage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SET_REMOTE_PROPERTY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SET_REMOTE_PROPERTY) ProtoMessage() {}

func (x *SET_REMOTE_PROPERTY) ProtoReflect() protoreflect.Message {
	mi := &file_ProxyMessage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SET_REMOTE_PROPERTY.ProtoReflect.Descriptor instead.
func (*SET_REMOTE_PROPERTY) Descriptor() ([]byte, []int) {
	return file_ProxyMessage_proto_rawDescGZIP(), []int{5}
}

func (x *SET_REMOTE_PROPERTY) GetPropertyMapList() []*PropertyMap {
	if x != nil {
		return x.PropertyMapList
	}
	return nil
}

// @message
type ADD_CLIENT_ACK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ComponentId int32  `protobuf:"varint,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	LoginAddr   string `protobuf:"bytes,2,opt,name=login_addr,json=loginAddr,proto3" json:"login_addr,omitempty"`
}

func (x *ADD_CLIENT_ACK) Reset() {
	*x = ADD_CLIENT_ACK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ProxyMessage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ADD_CLIENT_ACK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ADD_CLIENT_ACK) ProtoMessage() {}

func (x *ADD_CLIENT_ACK) ProtoReflect() protoreflect.Message {
	mi := &file_ProxyMessage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ADD_CLIENT_ACK.ProtoReflect.Descriptor instead.
func (*ADD_CLIENT_ACK) Descriptor() ([]byte, []int) {
	return file_ProxyMessage_proto_rawDescGZIP(), []int{6}
}

func (x *ADD_CLIENT_ACK) GetComponentId() int32 {
	if x != nil {
		return x.ComponentId
	}
	return 0
}

func (x *ADD_CLIENT_ACK) GetLoginAddr() string {
	if x != nil {
		return x.LoginAddr
	}
	return ""
}

var File_ProxyMessage_proto protoreflect.FileDescriptor

var file_ProxyMessage_proto_rawDesc = []byte{
	0x0a, 0x12, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x7a, 0x70, 0x62, 0x22, 0x7e, 0x0a, 0x08, 0x50, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x70, 0x5f, 0x69,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x49, 0x6e, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x70, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x5f, 0x66,
	0x6c, 0x6f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x70, 0x46, 0x6c, 0x6f,
	0x61, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x5f, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x70, 0x42, 0x6f, 0x6f, 0x6c, 0x22, 0x44, 0x0a, 0x0b, 0x50, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x79, 0x4d, 0x61, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x7a, 0x70, 0x62, 0x2e,
	0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x6e, 0x0a, 0x14, 0x41, 0x44, 0x44, 0x5f, 0x45, 0x4e, 0x47, 0x49, 0x4e, 0x45, 0x5f, 0x43, 0x4f,
	0x4d, 0x50, 0x4f, 0x4e, 0x45, 0x4e, 0x54, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6c,
	0x69, 0x73, 0x74, 0x65, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22,
	0x93, 0x01, 0x0a, 0x18, 0x41, 0x44, 0x44, 0x5f, 0x45, 0x4e, 0x47, 0x49, 0x4e, 0x45, 0x5f, 0x43,
	0x4f, 0x4d, 0x50, 0x4f, 0x4e, 0x45, 0x4e, 0x54, 0x5f, 0x41, 0x43, 0x4b, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x40, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x7a, 0x70,
	0x62, 0x2e, 0x41, 0x44, 0x44, 0x5f, 0x45, 0x4e, 0x47, 0x49, 0x4e, 0x45, 0x5f, 0x43, 0x4f, 0x4d,
	0x50, 0x4f, 0x4e, 0x45, 0x4e, 0x54, 0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x53, 0x0a, 0x13, 0x53, 0x59, 0x4e, 0x43, 0x5f, 0x50, 0x52,
	0x4f, 0x58, 0x59, 0x5f, 0x50, 0x52, 0x4f, 0x50, 0x45, 0x52, 0x54, 0x59, 0x12, 0x3c, 0x0a, 0x11,
	0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x5f, 0x6d, 0x61, 0x70, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x7a, 0x70, 0x62, 0x2e, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x4d, 0x61, 0x70, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x79, 0x4d, 0x61, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x53, 0x0a, 0x13, 0x53, 0x45,
	0x54, 0x5f, 0x52, 0x45, 0x4d, 0x4f, 0x54, 0x45, 0x5f, 0x50, 0x52, 0x4f, 0x50, 0x45, 0x52, 0x54,
	0x59, 0x12, 0x3c, 0x0a, 0x11, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x5f, 0x6d, 0x61,
	0x70, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x7a,
	0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x4d, 0x61, 0x70, 0x52, 0x0f,
	0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x4d, 0x61, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x22,
	0x52, 0x0a, 0x0e, 0x41, 0x44, 0x44, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x41, 0x43,
	0x4b, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x41,
	0x64, 0x64, 0x72, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x3b, 0x7a, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ProxyMessage_proto_rawDescOnce sync.Once
	file_ProxyMessage_proto_rawDescData = file_ProxyMessage_proto_rawDesc
)

func file_ProxyMessage_proto_rawDescGZIP() []byte {
	file_ProxyMessage_proto_rawDescOnce.Do(func() {
		file_ProxyMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_ProxyMessage_proto_rawDescData)
	})
	return file_ProxyMessage_proto_rawDescData
}

var file_ProxyMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ProxyMessage_proto_goTypes = []interface{}{
	(*Property)(nil),                 // 0: zpb.Property
	(*PropertyMap)(nil),              // 1: zpb.PropertyMap
	(*ADD_ENGINE_COMPONENT)(nil),     // 2: zpb.ADD_ENGINE_COMPONENT
	(*ADD_ENGINE_COMPONENT_ACK)(nil), // 3: zpb.ADD_ENGINE_COMPONENT_ACK
	(*SYNC_PROXY_PROPERTY)(nil),      // 4: zpb.SYNC_PROXY_PROPERTY
	(*SET_REMOTE_PROPERTY)(nil),      // 5: zpb.SET_REMOTE_PROPERTY
	(*ADD_CLIENT_ACK)(nil),           // 6: zpb.ADD_CLIENT_ACK
}
var file_ProxyMessage_proto_depIdxs = []int32{
	0, // 0: zpb.PropertyMap.value:type_name -> zpb.Property
	2, // 1: zpb.ADD_ENGINE_COMPONENT_ACK.component_list:type_name -> zpb.ADD_ENGINE_COMPONENT
	1, // 2: zpb.SYNC_PROXY_PROPERTY.property_map_list:type_name -> zpb.PropertyMap
	1, // 3: zpb.SET_REMOTE_PROPERTY.property_map_list:type_name -> zpb.PropertyMap
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ProxyMessage_proto_init() }
func file_ProxyMessage_proto_init() {
	if File_ProxyMessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ProxyMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Property); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ProxyMessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PropertyMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ProxyMessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ADD_ENGINE_COMPONENT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ProxyMessage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ADD_ENGINE_COMPONENT_ACK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ProxyMessage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SYNC_PROXY_PROPERTY); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ProxyMessage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SET_REMOTE_PROPERTY); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ProxyMessage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ADD_CLIENT_ACK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ProxyMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ProxyMessage_proto_goTypes,
		DependencyIndexes: file_ProxyMessage_proto_depIdxs,
		MessageInfos:      file_ProxyMessage_proto_msgTypes,
	}.Build()
	File_ProxyMessage_proto = out.File
	file_ProxyMessage_proto_rawDesc = nil
	file_ProxyMessage_proto_goTypes = nil
	file_ProxyMessage_proto_depIdxs = nil
}
